name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  macos:
    name: macOS ${{ matrix.configuration }}

    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: [debug, release]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-${{ matrix.configuration }}-spm-cache-${{ hashFiles('Package.resolved') }}

    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version


    - name: Build
      # if: matrix.configuration == 'release'
      run: swift build --configuration ${{ matrix.configuration }}

    #- name: Build & Test
    #  if: matrix.configuration == 'debug'
    #  run: swift test --configuration ${{ matrix.configuration }}
  linux:
    name: Linux ${{ matrix.linux }} ${{ matrix.configuration }}

    container:
      image: swift:${{ matrix.linux }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        linux: [bionic, xenial, focal, amazonlinux2, centos8]
        configuration: [debug, release]

    steps:
    - uses: actions/checkout@v2
    - name: Install libsqlite3
      if: ${{ !(startsWith( matrix.linux, 'centos' ) || startsWith( matrix.linux, 'amazonlinux' )) }}
      run: apt-get update && apt-get install -y --no-install-recommends libsqlite3-dev
    - name: Install libsqlite3
      if: ${{ startsWith( matrix.linux, 'centos' ) || startsWith( matrix.linux, 'amazonlinux' ) }}
      run: yum update -y && yum install -y sqlite-devel

    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-${{matrix.linux}}-${{ matrix.configuration }}-spm-cache-${{ hashFiles('Package.resolved') }}
    - name: Check Swift version
      run: swift --version

    - name: Build
      # if: matrix.configuration == 'release'
      run: swift build --configuration ${{ matrix.configuration }}

    #- name: Build & Test
    #  if: matrix.configuration == 'debug'
    #  run: swift test --configuration ${{ matrix.configuration }} --enable-test-discovery
